.PHONY: check test

check:
	go build -o /dev/null ./...
	cd gin && go build -o /dev/null ./...
	go vet ./...
	cd gin && go vet ./...
	gofmt -l .
	cd gin && gofmt -l .
	go mod verify && go mod tidy -v
	cd gin && go mod verify && go mod tidy -v

test:
	go test -p 1 -v -race -coverprofile=coverage.out ./...
	cd gin && go test -p 1 -v -race -coverprofile=coverage.out ./...
