.PHONY: check test

check:
	go build -o /dev/null ./...
	go vet ./...
	gofmt -l .
	go mod verify && go mod tidy -v

	cd chi && go build -o /dev/null ./...
	cd chi && go vet ./...
	cd chi && gofmt -l .
	cd chi && go mod verify && go mod tidy -v

	cd gin && go build -o /dev/null ./...
	cd gin && go vet ./...
	cd gin && gofmt -l .
	cd gin && go mod verify && go mod tidy -v

	cd fiber && go build -o /dev/null ./...
	cd fiber && go vet ./...
	cd fiber && gofmt -l .
	cd fiber && go mod verify && go mod tidy -v

test:
	go test -p 1 -v -race -coverprofile=coverage.out ./...
	cd chi && go test -p 1 -v -race -coverprofile=coverage.out ./...
	cd gin && go test -p 1 -v -race -coverprofile=coverage.out ./...
	cd fiber && go test -p 1 -v -race -coverprofile=coverage.out ./...
